Class {
	#name : 'AIAbstractChatTextElement',
	#superclass : 'Object',
	#category : 'AIAssistantCoreApp'
}

{ #category : 'Not categorized' }
AIAbstractChatTextElement >> isEmphasisElement [

	^ false
]

{ #category : 'Not categorized' }
AIAbstractChatTextElement >> isSequenceElement [

	^ false
]

{ #category : 'Not categorized' }
AIAbstractChatTextElement >> isStringElement [

	^ false
]
